# Generated by Django 3.2.4 on 2021-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
